### ISSUE TITLE
Error trying to connect: The certificate was not trusted

### ISSUE THREAD

**Issue by t0il3ts0ap** [davidB/kubectl-view-allocations#11]
```
$  kubectl-view-allocations -g resource
[2019-12-18T17:03:06Z ERROR kubectl_view_allocations] failed
    cli: CliOpts { namespace: None, show_zero: false, resource_name: [], group_by: [resource] }
    error: ReqwestError: error sending request for url (https://***************/api/v1/nodes?): error trying to connect: The certificate was not trusted.

    Caused by:
        0: error sending request for url (https://***************/api/v1/nodes?): error trying to connect: The certificate was not trusted.
        1: error trying to connect: The certificate was not trusted.
        2: The certificate was not trusted.
```

Get pods is working with my kubeconfig though. Also noticed a typo in above error.
```
$ kubectl get pods
NAME                                                     READY   STATUS    RESTARTS   AGE
***************-586b47d996-58wmz                       1/1     Running   0          5h21m
```

**Comment by davidB** [comment]
Sorry for the issue, it seems related to https://github.com/clux/kube-rs/issues/89.

Can you share after some obfuscation what look like your $HOME/.kube/config (I mainly need the key to have an idea of what kind of config I should reproduce, to be able to fix) ?

Thanks for give a try and reporting the bug

**Comment by t0il3ts0ap** [comment]
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority: /Users/anoop/.minikube/ca.crt
    server: https://192.168.64.2:8443
  name: minikube
- cluster:
    certificate-authority-data: ************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
    server: https://************************.in
  name: ********************.in
- cluster:
    certificate-authority-data: ************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
    server: https://**********************.in
  name: ******************.in
contexts:
- context:
    cluster: minikube
    user: minikube
  name: minikube
- context:
    cluster: ********************.in
    namespace: dev
    user: ********************.in
  name: non-prod
- context:
    cluster: ******************.in
    namespace: default
    user: ******************.in
  name: spike
current-context: non-prod
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: /Users/anoop/.minikube/client.crt
    client-key: /Users/anoop/.minikube/client.key
- name: ********************.in
  user:
    client-certificate-data: *******************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************=
    client-key-data: **************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************==
    password: ********************************
    username: *****
- name: **********************************
  user:
    password: ********************************
    username: *****
- name: ******************.in
  user:
    client-certificate-data: *******************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************=
    client-key-data: **************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************==
    password: ********************************
    username: admin
- name: ********************************
  user:
    password: ********************************
    username: *****
```
Had to * everything
